version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node # ジョブのコマンドが実行されるプライマリ コンテナ
    steps:
      - checkout # プロジェクト ディレクトリ内のコードをチェック アウトします
      - run : 
          name: Build front-end
          command: |
            npm install
            npm run build
  test:
    docker:
      - image: circleci/node:12-browsers # ジョブのコマンドが実行されるプライマリ コンテナ
    steps:
      - checkout # プロジェクト ディレクトリ内のコードをチェック アウトします
      - run : 
          name: Test front-end
          command: |
            npm install
            npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
workflows:
  my_workflow:
    jobs:
      - build
      - test:
         requires:
          - build
